### ISSUE TITLE
Collassare icone a destra

### ISSUE THREAD

**Issue by GISdevio-dev** [GISdevio/OSM-Accessibility-Web#1]
Aggiungere la possibilità di collassare il menù/le icone sulla destra, in modo da avere una visualizzazione più compatta.

**Comment by nicokant** [comment]
nella visuale desktop? possiamo valutare di usare unicamente il drawer per gestire i livelli come su mobile per avere il massimo della compattezza

**Comment by GISdevio-dev** [comment]
C'è un bug nella versione mobile: quando apro il menu dei layer (che sono tutti accesi), il pulsante dice 'Mostra tutti' mentre dovrebbe dire 'Nascondi tutti'. Una volta che viene cliccato, è tutto corretto (il pulsante diventa 'Nascondi tutti') e da lì in avanti funziona correttamente.

**Comment by nicokant** [comment]
Risolta la questione dello stato del toggle, per quanto riguarda il discorso di usare sempre il drawer?
