### ISSUE TITLE
Tragitto

### ISSUE THREAD

**Issue by CandidaMa** [GISdevio/OSM-Accessibility-Web#13]
Dopo aver stabilito il tragitto dal Punto A al punto B la  webapp deve poterti tracciare durante il percorso, così da capire a che punto sei rispetto al tragitto impostato

**Comment by GISdevio-dev** [comment]
La webapp offre la funzionalità di routing, non quella di navigazione (che richiederebbe peraltro una serie di considerazioni e sviluppi ulteriori).

Tuttavia, la funzionalità di visualizzazione della posizione dell'utente è stata già aggiunta da diverso tempo: l'utilizzo di questa funziona permette di fatto all'utente di vedere la propria posizione attuale in qualsiasi momento, ad esempio anche dopo aver calcolato un percorso e quindi durante lo spostamento lungo tale percorso.
