### ISSUE TITLE
Filtro sull'accessibilità dei POI

### ISSUE THREAD

**Issue by GISdevio-dev** [GISdevio/OSM-Accessibility-Web#15]
Sarebbe utile poter filtrare i POI su mappa non solo in base alla categoria, ma anche in base all'informazione sull'accessibilità (accessibile, non accessibile, accessibilità limitata).

2 ipotesi su come farlo:

* aggiungere un menu a tendina chiamato "Accessibilità", con 3 checkbox (di default) tutti e 4 selezionati: 'accessibile', 'non accessibile', 'accessibilità limitata', 'nessuna informazione sull'accessibilità'. L'utente toglie i check in base alle categorie di POI che vuole visualizzare - ad esempio se vuole vedere solo quelli accessibili, toglie tutti i check e lascia solo quello su 'accessibile'.

* stesso principio, ma aggiungere (ad esempio in alto a destra) una colonna verticale o una barra orizzontale con 4 icone (magari con il simbolo di una carrozzina) che corrispondono alle 4 categorie e di default sono tutti selezionati. Quando sono selezionate, le 3 icone sono blu; quando invece sono deselezonate, le icone diventano gialla, verde, rossa e grigia.

**Comment by nicokant** [comment]
implementato in a7c8fe39eaf7f97e431d89ff250e741188c814c7, deploy in corso

**Comment by GISdevio-dev** [comment]
Il filtro funziona correttamente, ma c'è un problema su schermi piccoli: il pulsante con la carrozzina non c'è. Quando si apre il pulsante che visualizza i layer, il pulsante con la carrozzina si dovrebbe comunque vedere al di sopra delle categorie.

**Comment by nicokant** [comment]
aggiunto in b39ae6a80b21544d7da5fda2786143b2dbf40f9a

![FireShot Capture 053 - Wikimedia OSM disability - localhost](https://user-images.githubusercontent.com/6927678/119102594-7af93300-ba1a-11eb-87b7-c139202a0117.png)

![FireShot Capture 059 - Wikimedia OSM disability - localhost](https://user-images.githubusercontent.com/6927678/119102735-a54af080-ba1a-11eb-9ba0-9365152f1c5b.png)
