### ISSUE TITLE
Compatibilità con Safari

### ISSUE THREAD

**Issue by ferdi2005** [GISdevio/OSM-Accessibility-Web#16]
Allo stato attuale, la webapp risulta incompatibile con Safari (Versione 14.1 (16611.1.21.161.6) – macOS Big Sur 11.3.1). Infatti, cliccando sui marker dei POI non si apre nessuna finestrella popover (come succede invece su Chrome).

[Video illustrativo](https://cln.sh/YnWrSV)

**Comment by nicokant** [comment]
Facendo un controllo il problema sembrerebbe legato a leaflet: https://github.com/Leaflet/Leaflet/issues/7255
Devo approfondire e capire se c'è un workaround

**Comment by GISdevio-dev** [comment]
@ferdi2005 grazie della segnalazione, il problema è stato risolto. Se confermi che va tutto bene, puoi chiudere direttamente la issue. Grazie!

**Comment by LorenzoStucchi** [comment]
Ho provato io con Macbook e Safari con le stesse specifiche indicate da @ferdi2005 e funziona tutto, lascio a lui la chiusura della issue

**Comment by ferdi2005** [comment]
Scusate per il ritardo, da Safari ora tutto ok! Grazie.
