### ISSUE TITLE
Problemi visualizzazione su iPhone

### ISSUE THREAD

**Issue by GISdevio-dev** [GISdevio/OSM-Accessibility-Web#2]
Sembra ci siano problemi di visualizzazione su iPhone 11, usando Safari:
* i pulsanti in basso a sinistra sono parzialmente nascosti, e i pulsanti in basso a destra (tasti di zoom) non si vedono
* i pulsanti a destra per accendere/spegnere i layer non si vedono del tutto
* nella finestra della nota, la parte a destra è tagliata

![IMG_2531](https://user-images.githubusercontent.com/76219273/112767168-6ea5ba80-9015-11eb-85d0-e6af27ff1689.PNG)
![IMG_2532](https://user-images.githubusercontent.com/76219273/112767172-6fd6e780-9015-11eb-8e8c-93a05c68e4c9.PNG)
![IMG_2533](https://user-images.githubusercontent.com/76219273/112767175-71a0ab00-9015-11eb-9275-5065c00d4a8f.PNG)

**Comment by GISdevio-dev** [comment]
Su iPhone 11, l'unico problema che riscontro con Safari è l'assenza dei due tasti di zoom in basso a sinistra. Tutti gli altri problemi io non li ho.
Su Firefox invece funziona tutto perfettamente.

**Comment by nicokant** [comment]
Si tratta di due problemi diversi:
- problema di zoom della UI (non della mappa)
- problema di calcolo dell'altezza della pagina

Ho risolto la seconda, pare che Safari si comporti in modo diverso per quanto riguarda le unità di misura in `vh` (viewport height) che in questo caso tengono conto dell'header del browser e di altri elementi, quindi la pagina risulta più alta ma la mappa impedisce di scrollare più sotto.
Ho rimosso i `height: 100vh` e impostato il calcolo esatto via JS dell'altezza della pagina.

Per quanto riguarda la prima è possibile riprodurla facendo pinch to zoom (ingrandendo) a partire da un elemento della UI che non sia la mappa. Ad esempio aprendo la modalità di navigazione e facendo zoom.
Non è possibile disabilitare questa funzionalità su Safari, ne credo sia consigliabile (visto che serve appunto per disabilità). Dovremmo però trovare un modo di tornare allo zoom di base senza rompere l'intera UI. Attaulmente quando si fa zoom in non sembra possibile tornare alla situazione di partenza

**Comment by GISdevio-dev** [comment]
Il problema si verifica (su qualsiasi browser) ogni volta che si clicca sul box di testo per scrivere qualcosa: quando si clicca, viene eseguito uno zoom. Quando si smette di scrivere, tutto resta 'zoommato' e da lì iniziano i problemi (che sono risolvibili solo facendo uno zoom all'indietro dall'elemento della UI, che però non è una cosa intuitiva).

Se lo zoom 'volontario' dell'utente sull'elemento della UI è un problema meno urgente (di norma l'utente non lo fa), questo è un problema più frequente perchè si verifica ogni volta che l'utente scrive nel box di testo.

Capire se il problema può essere evitato, ad esempio:

* forzando che quando si clicca il box di testo, non venga fatto lo zoom
* riportando la pagina allo zoom di default appena l'utente smette di scrivere nel box di testo

**Comment by nicokant** [comment]
Il problema era la dimensione del font che sotto i 16px su browser mobile fa sì che la pagina venga zoommata in automatico
