### ISSUE TITLE
Aggiungere più tag nei popup, dopo il click su un POI

### ISSUE THREAD

**Issue by GISdevio-dev** [GISdevio/OSM-Accessibility-Web#3]
Sarebbe utile avere più tag visualizzati nel popup che si apre quando si clicca un POI.

Se disponibili in OSM, potrebbero esserci almeno il tipo di tag principale, l'indirizzo, il numero di telefono e eventuali altri tag di contatto (sito web, facebook). Se possibile, potrebbe esserci anche il link per aprire l'elemento su openstreetmap.org, per vedere il tagging completo (forse è una funzionalità + da OSMer, però credo sia cmq utile).

___________

Ci sono almeno 3 opzioni possibili:

1) elencare i tag (chiavi e valori) così come sono in OSM, volendo anche con i link alla chiave e al valore (un po' come fatto in "Is OSM up-to-date", vedi screenshot sotto), ma questo può risultare poco intuitivo per un utente che non sa cosa sia OSM:

![immagine](https://user-images.githubusercontent.com/76219273/112767341-86317300-9016-11eb-8482-29cda0a0352c.png)

Quindi, in linea col suggerimento, l'elenco potrebbe essere questo:

    tag principale usato per classificare
    addr:city = XXX [se esiste]
    addr:street = XXX [se esiste]
    addr:postcode = XXX [se esiste]
    addr:housenumber = XXX [se esiste]
    frase 'Apri in OpenStreetMap' cliccabile con link al nodo su OSM

2) anzichè le chiavi così come sono in OSM, mettere le corrispondenti 'traduzioni' in italiano. Questo sarebbe forse molto più utile per utenti non esperti di OSM ma pone subito un problema, perché 'tradurre' i tag non sempre è possibile: ad esempio 'addr:housenumber' -> 'numero civico' funziona, ma 'addr:street' -> 'strada' non è corretto (potrebbe essere una piazza, un viale, ecc.).

3) un indirizzo si può 'ricreare' accostando semplicemente le info che si trovano nei vari campi (nome strada + numero civico + CAP + comune). Il problema è che potrebbero sempre esserci indirizzi 'parziali', ad es. con numero civico ma senza il nome della via, oppure solo con CAP e comune ma senza via e numero civico. Quindi ci sarebbero dei rischi.

**Comment by GISdevio-dev** [comment]
La soluzione condivisa è la 3. Si procede così:

**Indirizzo**: lo 'costruiamo' a mano in questo modo: valore del tag addr:street + ' ' + valore del tag addr:housenumber + ', ' + valore del tag addr:postcode + ' ' + valore del tag 'addr:city  --> ESEMPIO: 'Via Alessandro Volta 23, 20121 Milano'

* se ci sono solo la via e il numero civico, ma CAP e/o comune mancano, si completano a mano con '20121 Milano' (da verificare prima che nell'area di test il CAP sia sempre 20121)
* se manca il numero civico, non fa niente: si mette lo stesso la via, il CAP e il comune
* se manca la via ma c'è il numero civico, il numero civico non si mette (l'indirizzo non avrebbe senso)

**Tag principale**
* Dovrà comparire in alto in grassetto, dove adesso invece compare il contenuto del tag name. Il valore da visualizzare è la 'traduzione' in italiano del tag di OSM. Ad esempio amenity=restaurant sarà visualizzato come 'Ristorante'.

- [ ] GISdevio: identificare il file di configurazione in cui sono listate le chiavi e i valori che usiamo al momento per filtrare i POI su OSM. 
- [ ] Wikimedia Italia: aggiungere in questo documento, per ogni tag, la traduzione in italiano che si vuole visualizzate nel popup (fare una pull request).

* il contenuto del campo 'name' sarà visualizzato in testo normale sotto al testo in grassetto.

Riassumendo, nel popup avremo ad esempio (su 3 righe diverse):

**Ristorante**
Trattoria da Peppino
Via Alessandro Volta 23, 20121 Milano
informazione sull'accessibilità
tasto 'Vai'

Oppure (nel caso di un POI senza nome e senza indirizzo mappati)

**Fontanella**
informazione sull'accessibilità
tasto 'Vai'

**Comment by nicokant** [comment]
risolto nel commit 9eec3cb09070845233b7758f46c3f7334f6331db

è possibile modificare i testi ed eventualmente estenderli tramite questo file di configurazione
https://github.com/GISdevio/OSM-Accessibility-Web/blob/9eec3cb09070845233b7758f46c3f7334f6331db/src/constants.js#L138

in particolare i tag con valori generici `*` sono gestiti in un dizionario separato che agisce da fallback in caso non venga trovato il tag nella lista di quelli specifici.

Viene sempre mostrato il primo tag trovato, quindi in caso un elemento abbia due tag validi, verrà mostrato solo il primo per questioni di efficienza
