### ISSUE TITLE
Link per donazioni a Wikimedia Italia

### ISSUE THREAD

**Issue by GISdevio-dev** [GISdevio/OSM-Accessibility-Web#5]
Rimuovere link a Paypal e inserire link diretto alla pagina https://sostieni.wikimedia.it.

**Comment by nicokant** [comment]
ho modificato testo e link, ho cambiato il bottone in questo: https://fontawesome.com/icons/donate?style=solid
Secondo me è necessario tenere un'icona perchè su mobile altrimenti il bottone è troppo grande

**Comment by GISdevio-dev** [comment]
Nella versione desktop non si vede il simbolo del dollaro.

![immagine](https://user-images.githubusercontent.com/76219273/112900312-9e22f880-90e3-11eb-9922-7dc8555f09a8.png)

- [ ] Wikimedia Italia ci conferma se il testo attuale 'Sostieni Wikimedia' va bene o se va modificato, e come.

**Comment by CandidaMa** [comment]
Sarebbe meglio inserire la scritta 'Sostieni Wikimedia' con 'Sostieni Wikimedia Italia'

**Comment by nicokant** [comment]
corretto la scritta nel commit 85e0e04fafd965dca83b8e29eb594e6932436634
