### ISSUE TITLE
Icona sedia a rotelle

### ISSUE THREAD

**Issue by LorenzoStucchi** [GISdevio/OSM-Accessibility-Web#6]
Sarebbe preferibile avere questa icona della sedia a rotelle
https://accessibleicon.org/#use

Oppure visto che usate Font Awesome
https://fontawesome.com/icons/accessible-icon
fab fa-accessible-icon

**Comment by nicokant** [comment]
Ciao Lorenzo, grazie della segnalazione! ho cambiato l'icona
